# Generated by Django 5.2.10 on 2026-02-04 05:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_alter_student_regno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='regno',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
